[project]
name = "arc-exodus"
version = "0.1.0"
description = "Transfer bookmarks from Arc browser to Chrome"
readme = "README.md"
authors = [
    { email = "jt.totty1991@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
arc-exodus = "arc_exodus.cli:main"

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
